# Generated by Django 4.1.4 on 2022-12-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('money_made', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('price', models.IntegerField()),
                ('flavour', models.CharField(choices=[('Chocolate', 'Chocolate'), ('Pistachio', 'Pistachio'), ('Strawberry', 'Strawberry'), ('Mint', 'Mint')], max_length=20)),
                ('quantity', models.BigIntegerField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.truck')),
            ],
        ),
    ]
