# Generated by Django 4.1.4 on 2022-12-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='money_made',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='truck',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
